config/routes.rb
SimpV2::Application.routes.draw do

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"
  
  resources :supporters
    
  resources :users do
    resources :supporters do
      resources :comments
    end 
  end 
  resources :supporters do
    resources :comments
  end 

  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :supporters
  has_many :comments
  
  attr_accessor :password
 
  
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def index
    if session[:user_id] != nil 
      
        
        @users = User.all
        respond_to do |format|
          format.html # index.html.erb
          format.json { render :json => @users }
        end
        
        else
      
        redirect_to root_url, :notice => "Debe iniciar sesion."
        end
    end

  def create

    @user = User.new(params[:user])
    if @user.save
      if session[:user_super]
        redirect_to users_url
      else
        redirect_to @user, :notice => "Signed up!"
      end
#      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end
  
  def update
 
    @user = User.find(params[:id])
    
    respond_to do |format|
      if @user.update_attributes!(params[:user])
 
        format.html { redirect_to @user, :notice => 'El registro se actualizo con exito.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>


  <div class="field">
    <%= f.label :user_id, "Nombre de Usuario" %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :municipality, "Municipio" %><br />
    <%= f.text_field :municipality %>
  </div>
  <div class="field">
    <%= f.label :email, "Correo Electrónico" %><br />
    <%= f.text_field :email %>
  </div>
	
	<div class="field">
		<%= f.check_box :super %><%= f.label :super, "Administrador" %>
	</div>
	
	<div class="actions">
    	<%= f.submit "Guardar Cambios" %><%= link_to "Cancelar", @user%>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Usuarios <hr/></h1>
[ <%= link_to 'Simpatizantes', supporters_path %> ]
<table width="100%" style="border-color: #400080;
border-style: solid;
border-left-width: 1px;
border-bottom-width: 1px;
border-right-width: 1px;
border-top-width: 1px;">
  <tr class="header">
    <th>Nombre de Usuario</th>
    <th>Correo Electrónico</th>
    <th>Municipio</th>
<th>Tipo</th>
    <th colspan="3">Acciones</th>
  

  </tr>

<% @users.each do |user| %>
  <tr class="<%= cycle("odd_row", "even_row")%>">
    <td><%= user.user_id %></td>
    <td><%= user.email %></td>
    <td align="center"><%= user.municipality %></td>
	<td align="center">
	<% if user.super %>
		Administrador
	<% else %>
		Usuario
	<% end %>
	</td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Agregar Usuario', new_user_path %>

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	<p>
		<%= f.label :user_id, "Nombre de Usuario"%><br/>
		<%= f.text_field :user_id %>
	</p>
	
  <p>
    <%= f.label :email, "Correo Electrónico"%><br />
    <%= f.text_field :email %>
  </p>
<p><%= f.label :municipality, "Municipio"%><br/>
	<%= f.text_field :municipality %></p>
  <p>
  <p>
    <%= f.label :password, "Contraseña" %><br />
    <%= f.password_field :password %>
  </p>

    <%= f.label :password_confirmation, "Verificar Contraseña" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
	<p>
		<%= f.label :super, "Administrador"%>
		<%= check_box_tag 'Administrador', :super %>
	</p>
	
  <p class="button"><%= submit_tag(value="Guardar") %>&nbsp;<%= link_to 'Cancelar', users_path %></p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.user_id %></h1>
<p>
  <b>User:</b>
  <%= best_in_place @user, :user_id %>
</p>

<p>
  <b>Correo Electrónico:</b>
  <%= best_in_place @user, :email %>
</p>

<p>
  <b>Municipio:</b>
  <%= best_in_place @user, :municipality %>
</p>
<% if @user.super %>
	<p>Administrador</p>
<% else %>
	<p>Usuario</p>
<% end %>