config/routes.rb
SimpV2::Application.routes.draw do

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"
  
  resources :supporters
    
  resources :users do
    resources :supporters do
      resources :comments
    end 
  end 
  resources :supporters do
    resources :comments
  end 

  resources :sessions

end

app/models/supporter.rb
class Supporter < ActiveRecord::Base

  
  belongs_to :user
  has_many :comments
  validates_presence_of :first_name
  validates_presence_of :father_last_name
  validates_uniqueness_of :email
  
 


end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  # GET /supporters
  # GET /supporters.json
  def index
    @supporters = Supporter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @supporters }
    end
  end

  # GET /supporters/1
  # GET /supporters/1.json
  def show
    @supporter = Supporter.find(params[:id])
    
    #@supporter = Supporter.find params[:supporter_id]
    @new_comment = Comment.new(:supporter => @supporter)


    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @supporter }
    end
  end

  # GET /supporters/new
  # GET /supporters/new.json
  def new
    @supporter = Supporter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @supporter }
    end
  end

  # GET /supporters/1/edit
  def edit
    @supporter = Supporter.find(params[:id])
  end

  # POST /supporters
  # POST /supporters.json
  def create
    @supporter = Supporter.new(params[:supporter])

    respond_to do |format|
      if @supporter.save
        format.html { redirect_to @supporter, :notice => 'Supporter was successfully created.' }
        format.json { render :json => @supporter, :status => :created, :location => @supporter }
      else
        format.html { render :action => "new" }
        format.json { render :json => @supporter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /supporters/1
  # PUT /supporters/1.json
  def update
    @supporter = Supporter.find(params[:id])

    respond_to do |format|
      if @supporter.update_attributes(params[:supporter])
        format.html { redirect_to @supporter, :notice => 'El registro se actualizo con exito.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @supporter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /supporters/1
  # DELETE /supporters/1.json
  def destroy

    @supporter = Supporter.find(params[:id])
    @supporter.destroy

    respond_to do |format|
      format.html { redirect_to supporters_url }
      format.json { head :ok }
    end
    

  end
end

app/helpers/supporters_helper.rb
module SupportersHelper
end

app/views/supporters/_form.html.erb
<%= form_for(@supporter) do |f| %>
  <% if @supporter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supporter.errors.count, "error") %> prohibited this supporter from being saved:</h2>

      <ul>
      <% @supporter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table width="100%">
	<tr>
		<td>
			<div class="field">
		    <%= f.label :first_name, "Nombre" %><br />
		    <%= f.text_field :first_name %>
		  </div>
		</td>
		<td>
			<div class="field">
		    <%= f.label :father_last_name, "Apellido Paterno" %><br />
		    <%= f.text_field :father_last_name %>
		  </div>
		</td>
		<td>
			<div class="field">
		    <%= f.label :mother_last_name, "Apellido Materno" %><br />
		    <%= f.text_field :mother_last_name %>
		  </div>
		</td>
	</tr>
	<tr>
		<td>
			<div class="field">
				<%= f.label :gender, "Genero"%><br/>
				<%= f.radio_button :gender, 'Masculino', :checked => true%>
				<%= f.label :gender, 'Masculino', :value => 'Masculino' %>
				<%= f.radio_button :gender, 'Femenino' %>
				<%= f.label :gender, 'Femenino', :value => 'Femenino' %>
				
			</div>
		</td>
		<td>
			<div class="field">
				<%= f.label :nickname, "Apodo"%><br/>
				<%= f.text_field :nickname%>
			</div>
		</td>
		<td>
			&nbsp;
		</td>
	</tr>
	<tr>
		<td>
			<div class="field">
	    		<%= f.label :email, "Correo Electrónico" %><br />
	    		<%= f.text_field :email %>
	  		</div>
		</td>
		<td>
			<div class="field">
	    		<%= f.label :phone, "Teléfono" %><br />
	    		<%= f.text_field :phone %>
	  		</div>
		</td>
		<td>
	  		<div class="field">
	    		<%= f.label :cellphone, "Celular" %><br />
	    		<%= f.text_field :cellphone %>
	  		</div>
		</td>
	</tr>
	<tr>
		<td>
			<div class="field">
	    		<%= f.label :street_address, "Domicilio" %><br />
	    		<%= f.text_field :street_address %>
	  		</div>
		</td>
		<td>
			<div class="field">
				<%= f.label :internal_number, "Número Interior"%><br/>
				<%= f.text_field :internal_number %>
			</div>
		</td>
		<td>
			<div class="field">
				<%= f.label :external_number, "Número Exterior" %><br/>
				<%= f.text_field :external_number %>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<div class="field">
				<%= f.label :neighborhood, "Colonia" %><br/>
				<%= f.text_field :neighborhood %>
			</div>
		</td>
		<td>
			<div class="field">
	    		<%= f.label :municipality, "Municipio" %><br />
	    		<%= f.text_field :municipality %>
	  		</div>
		</td>
		<td>
			<div class="field">
				<%= f.label :between_streets, "Entre las calles" %><br/>
				<%= f.text_field :between_streets %>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<div class="field">
	    		<%= f.label :section, "Sección" %><br />
	    		<%= f.text_field :section %>
	  		</div>
		</td>
		<td>
			<div class="field">
	    		<%= f.label :code, "Clave Electoral" %><br />
	    		<%= f.text_field :code %>
	  		</div>
		</td>
		<td>
			<div class="field">
				<%= f.label :type_of_card, "Credencial"%><br/>
				<%= f.radio_button :type_of_card, 'No Sabemos', :checked => true %>
				<%= f.label :type_of_card, 'No Sabemos', :value => 'No Sabemos' %>
				<%= f.radio_button :type_of_card, '03' %>
				<%= f.label :type_of_card, '\'03', :value => '03' %>
				<%= f.radio_button :type_of_card, 'Nueva' %>
				<%= f.label :gender, 'Nueva', :value => 'Nueva' %>
			
			</div>
		</td>
	</tr>
	</table>



 



 
  <div class="actions">
    <%= submit_tag(value="Guardar") %> <%= link_to 'Cancelar', @supporter %> 
  </div>
<% end %>

app/views/supporters/edit.html.erb
<h1>Editar Simpatizante<hr/></h1>
<p>
	[
	<%= link_to 'Simpatizantes', supporters_path %>
	
	
	]
</p>
<%= render 'form' %>

app/views/supporters/index.html.erb
<% 
	if params[:user_id] != nil
		@user = User.find(params[:user_id])		
	else
		@user = User.find(session[:user_id]) if session[:user_id]
	end
%>

<h1>Mis Simpatizantes<hr/></h1>
<p>
	[ <%= link_to 'Nuevo Simpatizante', new_supporter_path %>  
	<% if session[:user_super] %>
		| <%= link_to 'Nuevo Usuario', new_user_path %>
		| <%= link_to 'Usuarios', users_path %>
	<% end %>
	]
</p>
<table width="100%" style="border-color: #400080;
border-style: solid;
border-left-width: 1px;
border-bottom-width: 1px;
border-right-width: 1px;
border-top-width: 1px;">
  <tr class="header">
    <th>Nombre</th>
    <th>Correo Electrónico</th>
    <th>Teléfono</th>
    <th>Celular</th>


    <th>Codigo Electoral</th>
    <th>Sección</th>
<% if session[:user_super] %>
    <th>Acciones</th>
<% end %>
  </tr>


<% @supporters.each do |supporter| %>
  <tr class="<%= cycle("odd_row", "even_row")%>">
    <td><%= link_to supporter.first_name + " " + supporter.father_last_name + " " + supporter.mother_last_name, supporter %></td>
    <td><%= supporter.email %></td>
    <td><%= supporter.phone %></td>
    <td><%= supporter.cellphone %></td>


    <td><%= supporter.code %></td>
    <td><%= supporter.section %></td>

    <% if session[:user_super] %>
    <td align="center"><%= link_to 'Eliminar', supporter, :confirm => '¿Esta seguro? Esta acción no se puede deshacer.', :method => :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

app/views/supporters/new.html.erb
<h1>Nuevo Simpatizante</h1>



<%= render 'form' %>

app/views/supporters/show.html.erb
<h1><%= @supporter.first_name %>&nbsp;<%= @supporter.father_last_name %>&nbsp;<%= @supporter.mother_last_name %><hr/></h1>
<p>[
	<%= link_to 'Simpatizantes', supporters_path %>  
	|
	<%= link_to 'Editar', edit_supporter_path(@supporter) %> 
	]
	
</p>
<h3>Información Personal</h3>
<div style="background: #eeeeee">
<table width="100%">
	<tr>
		<td>
			<b>Genero:</b>
		</td>
		<td>
			<%= @supporter.gender%>
		</td>
		<td>
			<b>Sobrenombre:</b>
		</td>
		<td>
			"<%= best_in_place @supporter, :nickname %>"
		</td>
		<td>
			&nbsp;
		</td>
		<td>
			&nbsp;
		</td>
	</tr>
	<tr>
		<td>
			
		  		<b>Correo Electrónico:</b>
		</td>
		<td>
		  		<%= @supporter.email %>
			
		</td>
		<td>
			
			  <b>Teléfono:</b>
		</td>
		<td>
			  <%= @supporter.phone %>
			
		</td>
		<td>
			  <b>Celular:</b>
		</td>
		<td>
			  <%= @supporter.cellphone %>
		</td>
	</tr>
	<tr>
		<td>
			  <b>Domicilio:</b>
		</td>
		<td>
			  <%= @supporter.street_address %>
		</td>
		<td>
			<b>No. Exterior:</b>
		</td>
		<td>
			<%= @supporter.internal_number %>
		</td>
		<td>
			<b>No. Interior:</b>
		</td>
		<td>
			<%= @supporter.external_number %>
		</td>
	</tr>
	<tr>
		<td>
			<b>Colonia:</b>
		</td>
		<td>
			<%= @supporter.neighborhood %>
		</td>
		<td>
			  <b>Municipio:</b>
		</td>
		<td>
			  <%= @supporter.municipality %>
		</td>
		<td>
			<b>Entre las calles:</b>
		</td>
		<td>
			<%= @supporter.between_streets %>
		</td>
	</tr>
	<tr>
		<td>
			  <b>Sección:</b>
		</td>
		<td>
			<%= @supporter.section %>
		</td>
		<td> 
			<b>Clave Electoral:</b>
		</td>
		<td>
		  	<%= @supporter.code %>
		</td>
		<td><b>Tipo de Credencial:</td>
		<td><%= @supporter.type_of_card %></td>
	</tr>
</table>
</div>


<h3>Comentarios</h3>


<% if @supporter.comments.empty? %>
	<p>Aún no hay comentarios sobre este simpatizante. ¿Deseas agregar un comentario?</p>
<% else %>
<div id="comments">
	<table width="100%">
		<tr><th>Contacto</th><th>Fecha</th><th>Comentario</th>
	<%= render :partial => @supporter.comments %>
	</table>
</div>
<% end %>

<h3>Nuevo Comentario</h3>
<div style="background: #eeeeee">
<%= form_for [@supporter, @new_comment] do |f| %>
	<p>
		<p><b><%= f.label :contact_type, "Tipo de Contacto" %></b><br/>
		<%= f.radio_button :contact_type, 'Correo Electrónico', :checked => true%>
		<%= f.label :contact_type, 'Correo Electrónico', :value => 'Correo Electrónico' %>
		<%= f.radio_button :contact_type, 'Llamada' %>	
		<%= f.label :contact_type, 'Llamada', :value => 'Llamada' %>
		<%= f.radio_button :contact_type, 'Visita'%>
		<%= f.label :contact_type, 'Visita', :value => 'Visita' %>
		<%= f.radio_button :contact_type, 'SMS' %>
		<%= f.label :contact_type, 'SMS', :value => 'SMS' %>
</p>
		<p>
		<b><%= f.label :content, "Comentario" %></b><br/>
		<%= f.text_area :content, :cols => "132", :rows => "10"%></p>

	</p>
	<p>
		<%= f.submit "Agregar Comment"%>
	</p>
<% end %>
</div>